### ISSUE TITLE
Make the module require Backdrop core v1.23.0

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/entity_cache_admin#1]
It is my understanding that this module uses the feature introduced in https://github.com/backdrop/backdrop-issues/issues/5632, which only got merged into 1.23.0. We should add a dependency on the respective version of the core system module in the .info file of this module (and then create a release?).

**Comment by klonos** [comment]
PR for this here: https://github.com/backdrop-contrib/entity_cache_admin/pull/2

**Comment by bugfolder** [comment]
Agreed. Thanks for the reminder and the PR, @klonos!
